version: '3.8'

services:
  backend:
    image: novjhg/eurekabank_backend:v1
    container_name: eurekabank_backend
    ports:
      - "8081:8081"
    networks:
      - eurekanet

  frontend:
    image: novjhg/eurekabank_frontend:v1
    container_name: eurekabank_frontend
    ports:
      - "8080:8080"
    depends_on:
      - backend
    networks:
      - eurekanet

networks:
  eurekanet:
    driver: bridge
