server:
  port: 9090

spring:
  application:
    name: msvc-deposito
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/banquito
    username: root
    password: tu_contraseña
    hikari:
      minimum-idle: 5
      maximum-pool-size: 10
      auto-commit: true
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect

  config:
    import: optional:configserver:http://localhost:8888

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

cors:
  allowed-origins: "*"
  allowed-methods: "GET, POST, PUT, DELETE, OPTIONS"
  allowed-headers: "Content-Type, Authorization"
  allow-credentials: true
